---

- name: PHP | Installing packages
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - mod_php70u-{{php_version}} 
    - php70u-cli-{{php_version}}
    - php70u-mysqlnd-{{php_version}}
    - php70u-fpm-nginx-{{php_version}}
    - php70u-mcrypt-{{php_version}}
    - php70u-devel-{{php_version}}
    - php70u-json-{{php_version}}
    - php70u-mbstring-{{php_version}}
  notify:
    - restart nginx
    - restart php-fpm

- name: ensure php-fpm cgi.fix_pathinfo=0
  lineinfile: dest=/etc/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
  notify:
    - restart php-fpm
    - restart nginx

- name: Configuring PHP-FPM
  copy: src=www.conf dest=/etc/php-fpm.d/www.conf
  notify:
    - restart php-fpm

- name: Download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer
  register: composer_downloaded

- name: Install composer
  shell: php /tmp/composer --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
  when: composer_downloaded.changed
