---
# Install and configure build tools.

- name: install gcc
  yum: name=gcc
       state=present

- name: Install epel-release
  yum: name=epel-release
       state=present

# Install IUS

- name: Download IUS Project install script
  get_url: url=https://setup.ius.io/
           dest=/tmp/ius.sh

- name: Install IUS
  shell: bash /tmp/ius.sh
  ignore_errors: yes

# Install git

- name: Installing git
  yum:
    name: git
    state: present
